spring.application.name=simulator

# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:bankdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# to allow H2 db Console at http://localhost:8080/h2-console
spring.h2.console.enabled=true

# JPA/hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
